/*
 * screen-list.h -- give screens generated by tools/bin_header.c
 *                  utility a generic name
 */


#ifndef __SCREEN_LIST_H__
#define __SCREEN_LIST_H__

typedef enum {
	SCREEN_NONE = 0,
	SCREEN_LOW_BATTERY,
	SCREEN_NORMAL,
	SCREEN_TUNEUP_NO_VBUS,
	SCREEN_TUNEUP_VBUS,
	SCREEN_TUNEUP_VBUS_WALL,
	SCREEN_REFRESH,
	SCREEN_CHARGING,
	SCREEN_DISCONNECT_ERROR,
} screen_state;

typedef enum {
	SCREEN_NO_RES = 0,
	SCREEN_320_200,
	SCREEN_480_272,
	SCREEN_800_480,
	SCREEN_1024_600,
} screen_res;

void run_screen_state(screen_state new_screen_state);

/* match screen to screen bitmap char structure	*/
#if (defined(CONFIG_MACH_NXP3200_L2K_DTK))
#define	LOGO_SCREEN				l2k_lucy_boot_logo_320_200_bmp_gz
#define	CONNECTED_SCREEN		l2k_UI_Status_Downloading_320_200_bmp_gz
#define DOWNLOAD_TIMEOUT_SCREEN	l2k_UI_DownloadTimeout_320_200_bmp_gz
#define LOW_BATTERY_SCREEN		l2k_UI_Status_LowBattery_320_200_bmp_gz
#define SYSTEM_ATTENTION_SCREEN	l2k_UI_DownloadFailure_320_200_bmp_gz
#endif

#if (defined(CONFIG_MACH_NXP3200_M2K_DTK))
#define LOGO_SCREEN				m2k_boot_logo_480_272_bmp_gz
#define	CONNECTED_SCREEN		m2k_boot_connect_480_272_bmp_gz
#define DOWNLOAD_TIMEOUT_SCREEN	m2k_boot_download_timeout_480_272_bmp_gz
#define LOW_BATTERY_SCREEN		m2k_boot_battery_low_480_272_bmp_gz
#define SYSTEM_ATTENTION_SCREEN	m2k_boot_download_failure_480_272_bmp_gz
#endif

#if (defined(CONFIG_MACH_NXP3200_RIO_DTK))
#define LOGO_SCREEN					rio_boot_logo_1024_600_bmp_gz
#define	CONNECTED_SCREEN			rio_boot_connect_1024_600_bmp_gz
#define DOWNLOAD_TIMEOUT_SCREEN		rio_boot_download_timeout_1024_600_bmp_gz
#define LOW_BATTERY_SCREEN			rio_boot_battery_low_1024_600_bmp_gz
#define SYSTEM_ATTENTION_SCREEN		rio_boot_download_failure_1024_600_bmp_gz
#define CONNECTED_WALL_SCREEN		rio_boot_connect_wall_1024_600_bmp_gz
#define CHARGING_SCREEN				rio_boot_charging_1024_600_bmp_gz
#define DISCONNECT_ERROR_SCREEN		rio_boot_disconnect_error_1024_600_bmp_gz
#endif

#if (defined(CONFIG_MACH_NXP3200_VTK_DTK))
#define LOGO_SCREEN			vtk_boot_logo_800_480_bmp_gz
#define	CONNECTED_SCREEN		vtk_boot_connect_800_480_bmp_gz
#define DOWNLOAD_TIMEOUT_SCREEN	vtk_boot_download_timeout_800_480_bmp_gz
#define LOW_BATTERY_SCREEN		vtk_boot_battery_low_800_480_bmp_gz
#define SYSTEM_ATTENTION_SCREEN	vtk_boot_download_failure_800_480_bmp_gz
#endif

/* define bitmaps for reference */
#if (defined(CONFIG_MACH_NXP3200_L2K_DTK))
extern unsigned char L2K_LOGO_SCREEN_320_200[];
extern unsigned char L2K_CONNECTED_SCREEN_320_200[];
extern unsigned char L2K_DOWNLOAD_TIMEOUT_SCREEN_320_200[];
extern unsigned char L2K_LOW_BATTERY_SCREEN_320_200[];
extern unsigned char L2K_SYSTEM_ATTENTION_SCREEN_320_200[];
#endif

#if (defined(CONFIG_MACH_NXP3200_M2K_DTK))
extern unsigned char M2K_LOGO_SCREEN_480_272[];
extern unsigned char M2K_CONNECTED_SCREEN_480_272[];
extern unsigned char M2K_DOWNLOAD_TIMEOUT_SCREEN_480_272[];
extern unsigned char M2K_LOW_BATTERY_SCREEN_480_272[];
extern unsigned char M2K_SYSTEM_ATTENTION_SCREEN_480_272[];
#endif

#if (defined(CONFIG_MACH_NXP3200_RIO_DTK))
extern unsigned char RIO_LOGO_SCREEN1024_600[];
extern unsigned char RIO_CONNECTED_SCREEN1024_600[];
extern unsigned char RIO_DOWNLOAD_TIMEOUT_SCREEN1024_600[];
extern unsigned char RIO_LOW_BATTERY_SCREEN1024_600[];
extern unsigned char RIO_SYSTEM_ATTENTION_SCREEN1024_600[];
extern unsigned char RIO_CONNECTED_WALL_SCREEN1024_600[];
extern unsigned char RIO_CHARGING_SCREEN1024_600[];
extern unsigned char RIO_DISCONNECT_ERROR_SCREEN1024_600[];
#endif

#if (defined(CONFIG_MACH_NXP3200_VTK_DTK))
extern unsigned char VTK_LOGO_SCREEN_800_480[];
extern unsigned char VTK_CONNECTED_SCREEN_800_480[];
extern unsigned char VTK_DOWNLOAD_TIMEOUT_SCREEN_800_480[];
extern unsigned char VTK_LOW_BATTERY_SCREEN_800_480[];
extern unsigned char VTK_SYSTEM_ATTENTION_SCREEN_800_480[];
#endif

#endif /* __SCREEN_LIST_H__ */
